{% set name = "prefect" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aab5b5507b112f3739a3f1d30bd10b09a4df3b69e98cbabf6e71bee267361ea1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps -vv ."
  entry_points:
    - prefect = prefect.cli:cli

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - click >=7.0,<8.0
    - cloudpickle >=0.6.0,<1.3
    - croniter >=0.3,<0.4
    - dask >=0.18,<3.0
    - distributed >=1.26.1,<3.0
    - docker-py >=3.4.1,<5.0
    - marshmallow >=3.0.0b19,<4.0.0
    - marshmallow-oneofschema >=2.0.0b2,<3.0
    - mypy_extensions >=0.4.0,<0.5
    - pendulum >=2.0.2,<3.0
    - python-dateutil >2.7.3,<3.0
    - python-slugify >=1.2.6,<4.0
    - pyyaml >=3.13,<5.2
    - pytz >=2018.7
    - requests >=2.20,<3.0
    - tabulate >=0.8.0,<0.9.0
    - toml >=0.9.4,<1.0
    - typing >=3.6.4,<4.0
    - typing_extensions >=3.6.4,<4.0

test:
  imports:
    - prefect
    - prefect.triggers
    - prefect.schedules
    - prefect.tasks.shell
    - prefect.tasks.control_flow
    - prefect.tasks.github
    - prefect.tasks.templates
    - prefect.tasks.templates.jinja2

about:
  home: https://github.com/PrefectHQ/prefect
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'The Prefect Core automation engine '
  description: |
    Prefect is a new workflow management system, designed for modern
    infrastructure and powered by the open-source Prefect Core workflow engine.
    Users organize `Tasks` into `Flows`, and Prefect takes care of the rest.
  doc_url: https://docs.prefect.io/

extra:
  recipe-maintainers:
    - cicdw
    - dhirschfeld
    - rzillman
