travis:
  secure:
    BINSTAR_TOKEN: ZWoKZktkBcbP4NvbCDLPo/09mRjhGueKxtE/zrH62i1Av6w/UDQBbiekpGMtudWaxqbUySzvtKDpIMnhjecmO4gNnpyquSuAvKoFN06bW7wftULcxMYh2+e8mKDggXLLcRR4l6gi2uu/QsoO7cA0L2rYudSSEZwDw1YRmx9ZTE+uQm3oANFYt8+djJ3yhLuj5f4r97CVcgG4RYl6Ha496XVzrt/gfcKj5RpbDLYCKcJLPSl+WXmz8xAsf3Ia+zSVuYR4YGlDTwyaTcRcS/rfWM3XIkZO7f1Mcw/J2o9GHoLCwoCM73WMUxKqEbVDm4wgT5BGi0xVSxMCDKbK+8Jd7iEjnMqgfoZbpqI28sknE66k7SofaAOFnU88tSA1ajzJHb1eSz4MWEzZo5auDjJo+p9Bh/KWaRjdaIMiFMhbgYvDnvJ63B3vaH4WwP6iymjUXsSMDA0tLXUSWJ/kog213lR0MByKSgz3gKhC2MGXj5F2nXialQP+0+rJCXf5vNZ1qGMonzHlJtxCsqLbmxnMkbS3pJSXpFALcgRIGqWdIho+6qZIpKKjIBgZZeIzPSbblNdYZCoFnIkEmaoVPlnylASuw/F++zkdR5Tu00l9QDsh4EEwZ57rB0MLx8eXVKdYkL30hVFAp5289LeqjE5VNqmxm1/+TOK4Ri6yZrdyQVM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
